apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
spec:
  ttlSecondsAfterFinished: 60
  activeDeadlineSeconds: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: demo
        image: busybox
        command: ["sh", "-c", "echo Hello EKS! && sleep 600"]