apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: "${node_class_name}"
spec:

  role: "${eks_auto_node_policy}"

  # Required: Subnet selection for node placement
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${tag_subnet_value}"

  # Required: Security group selection for nodes
  securityGroupSelectorTerms:
     - tags:
         Name: "${tag_node_sg_name_value}"

  # Optional: Configure SNAT policy (defaults to Random)
  snatPolicy: Random  # or Disabled

  # Optional: Network policy configuration (defaults to DefaultAllow)
  networkPolicy: DefaultAllow  # or DefaultDeny

  # Optional: Network policy event logging (defaults to Disabled)
  networkPolicyEventLogs: Disabled  # or Enabled

  # Optional: Configure ephemeral storage (shown with default values)
  ephemeralStorage:
    size: "80Gi"    # Range: 1-59000Gi or 1-64000G or 1-58Ti or 1-64T
    iops: 3000      # Range: 3000-16000
    throughput: 125 # Range: 125-1000

  # IAM role to use for EC2 instance role
  # If unspecified, EKS will create a role
  # If specified, role requires access entry described above
  # role: arn:aws:iam::123456789012:role/MyNodeRole

  # # Optional: Additional EC2 tags
  # tags:
  #   Environment: "production"
  #   Team: "platform"
